#' supporting function for HFE
.HFE = function(brk, class_level, corr_cutoff=0.5, quiet=TRUE){
  tax_levs = c('Species', 'Genus', 'Family', 'Order', 'Class', 'Phylum', 'Domain')
  class_level = enexpr(class_level)
  # creating aggregated features
  dt_levs = list()
  if(as.character(class_level) %in% tax_levs[1:length(tax_levs)]){
    dt_levs[['Species']] = brk %>%
      dt_mutate(Taxonomy = paste(Phylum, Class, Order, Family, Genus, Species, sep=';'))  %>%
      dt_select(Taxonomy, Sample, Abundance)
  }
  if(as.character(class_level) %in% tax_levs[2:length(tax_levs)]){
    dt_levs[['Genus']] = brk %>%
      dt_mutate(Taxonomy = paste(Phylum, Class, Order, Family, Genus, sep=';')) %>%
      dt_summarize(Abundance = sum(Abundance),
                   by = list(Taxonomy, Sample))
  }
  if(as.character(class_level) %in% tax_levs[3:length(tax_levs)]){
    dt_levs[['Family']] = brk %>%
      dt_mutate(Taxonomy = paste(Phylum, Class, Order, Family, sep=';')) %>%
      dt_summarize(Abundance = sum(Abundance),
                   by = list(Taxonomy, Sample))
  }
  if(as.character(class_level) %in% tax_levs[4:length(tax_levs)]){
    dt_levs[['Order']] = brk %>%
      dt_mutate(Taxonomy = paste(Phylum, Class, Order, sep=';')) %>%
      dt_summarize(Abundance = sum(Abundance),
                   by = list(Taxonomy, Sample))
  }
  if(as.character(class_level) %in% tax_levs[5:length(tax_levs)]){
    dt_levs[['Class']] = brk %>%
      dt_mutate(Taxonomy = paste(Phylum, Class, sep=';')) %>%
      dt_summarize(Abundance = sum(Abundance),
                   by = list(Taxonomy, Sample))
  }
  if(as.character(class_level) %in% tax_levs[6:length(tax_levs)]){
    dt_levs[['Phylum']] = brk %>%
      dt_rename('Taxonomy' = Phylum) %>%
      dt_summarize(Abundance = sum(Abundance),
                   by = list(Taxonomy, Sample))
  }
  # combining & creating wide table
  brk = data.table::rbindlist(dt_levs, use.names=TRUE)
  rm(dt_levs)
  brk_w = brk %>%
    dt_pivot_wider(names_from=Taxonomy, values_from=Abundance)

  # correlation amoung features
  options(warn=-1)
  descrCor = brk_w %>%
    as_tibble %>%
    dplyr::select(-Sample) %>%
    cor %>% as.matrix
  options(warn=0)
  if(ncol(descrCor) > 1){
    descrCor[is.na(descrCor)] = 0
    to_rm = caret::findCorrelation(descrCor, cutoff=corr_cutoff, names=TRUE)
  } else {
    to_rm = c()
  }
  if(quiet == FALSE){
    cat('Clade: ', clade, sep = '')
    cat('; Removing', length(to_rm), 'of', ncol(brk_w)-1, 'taxa\n')
  }
  if(length(to_rm) > 0){
    brk = brk %>%
      dt_filter(Taxonomy %in% !!to_rm)
  }
  return(brk)
}

#' Hierachical Feature Selection
#'
#' For each clade (defined by tax_level), aggregate species abundances at each taxonomic
#' level up to the user-defined "tax_level", then filter out taxa that correlate strongly
#' (just one taxon is selected of those that correlate).
#'
#' @param brk data.table generated by read_bracken()
#' @param tax_level which taxonmoic level to use?
#' @param corr_cutoff features with >cutoff will be filtered to just one
#' @return data.table of filtered features
ml_tax_HFE = function(brk, tax_level, corr_cutoff=0.7, threads=2, quiet=TRUE){
  tax_level = enexpr(tax_level)
  if(as.character(tax_level) == 'Species'){
    brk = brk %>%
      dt_mutate(Taxonomy = paste(Phylum, Class, Order, Family, Genus, Species, sep=';')) %>%
      dt_select(Taxonomy, Abundance, Sample) %>%
      dt_pivot_wider(names_from=Taxonomy, values_from=Abundance)
    return(brk)
  }
  if(threads > 1) doParallel::registerDoParallel(threads)
  brk = brk %>%
    dt_group_split(!!tax_level) %>%
    plyr::llply(.HFE, class_level=!!tax_level,
                corr_cutoff=corr_cutoff, quiet=quiet,
                .parallel=threads > 1) %>%
    data.table::rbindlist(use.names=TRUE) %>%
    dt_pivot_wider(names_from=Taxonomy, values_from=Abundance)
  return(brk)
}
